// GENERATED by tool/sync_l10n.dart from apps/web/src/i18n and lib/l10n/catalog.
// Do not edit: run `npm run l10n:sync` (or `dart run tool/sync_l10n.dart` in apps/mobile).
// Kiswahili strings are provisional until a native speaker reviews them (#221).

/// Every UI message by locale and key, read by LectioLocalizations.
const String catalogJson = r'''
{
  "en": {
    "Zeta_retry": "Try {what} again in {seconds}s",
    "Zeta_empty": "",
    "app_close": "Close",
    "app_count": "Showing {count} of {total}",
    "day_title": "Today",
    "day_b": "A repeated key keeps its first place and takes the last value",
    "day_2": "An integer-like key keeps its place",
    "day_masses": {
      "zero": "No Masses",
      "one": "{count} Mass",
      "many": "{count} Masses (many)",
      "other": "{count} Masses"
    },
    "day_notes": {
      "few": "{count} notes ({kind})",
      "other": "{count} notes ({kind})"
    },
    "day_slot_psalm": "Psalm {n}",
    "day_slot_other": "Other links",
    "day_slot_nested_deep": "Quote \"this\", a back\\slash, a tab\t, a slash / and a control \u0001 character",
    "day_unicode": "Kiswahili, Ελληνικά, עברית, emoji 😀, line separator and a lone \ud800 surrogate"
  },
  "sw": {
    "Zeta_empty": "",
    "Zeta_retry": "Jaribu {what} tena baada ya sekunde {seconds}",
    "app_close": "Funga",
    "app_count": "Inaonyesha {count} kati ya {total}",
    "day_2": "Ufunguo kama nambari",
    "day_title": "Leo",
    "day_b": "Ufunguo wa pili",
    "day_masses": {
      "one": "Misa {count}",
      "other": "Misa {count}"
    },
    "day_notes": {
      "one": "maelezo {count} ({kind})",
      "other": "maelezo {count} ({kind})"
    },
    "day_slot_nested_deep": "Nukuu \"hii\" \\ /",
    "day_slot_psalm": "Zaburi {n}",
    "day_slot_other": "Viungo vingine",
    "day_unicode": "Kiswahili 😀"
  }
}
''';
